# docker-compose.dbadmin.yml
version: "3"

services:
    
#################################
# phpmyadmin:
#     image: phpmyadmin:5.0
#     restart: always
#     ports: 
#         - 8080:80
#     environment: 
#         - PMA_ARBITRARY=1
#     external_links:
#         - mysql:mysql
#     networks:
#         - web

#############
# SQL
#
# https://sqlectron.github.io/
#
##############

    ############
    # tips: don't use networks => not find
    # use different name for volume and service
    ############
    mongo-express:
        image: mongo-express
        restart: always
        volumes:
            - mongo-v
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        # networks: DO NOT USE !

    mongo-client:
        image: mongoclient/mongoclient
        restart: always
        volumes:
            - mongo-v:/data/db
        environment:
            - MONGO_URL=mongodb://root:root@mongo:27017
            - MONGOCLIENT_AUTH=TRUE
            - MONGOCLIENT_USERNAME=root
            - MONGOCLIENT_PASSWORD=root
        ports:
            - 8082:3000
        # networks: DO NOT USE !

    mongo-gui:
        image: ugleiton/mongo-gui
        restart: always
        volumes:
            - mongo-v:/data/db
        ports:
            - 8083:4321
        environment:
            - MONGO_URL=mongodb://root:root@mongo:27017
        # networks: DO NOT USE !

    mongoku:
        image: huggingface/mongoku
        restart: always
        volumes:
            - mongo-v:/data/db
        ports: 
            - 8084:3100
        environment:
            - MONGOKU_DEFAULT_HOST=mongodb://root:root@mongo:27017
        # networks: DO NOT USE !

volumes:
    mongo-v:

networks:
    web: