version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        #container_name: nginx
        ports:
            - 82:80
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        networks: 
            - zend
          
    phpfpm: 
        build: .docker/conf/fpm
        working_dir: /appli
        ports: 
            - 9002:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
        #depends_on: 
        #    - ldap-server
        networks: 
            - zend
    
    # ldap-server:
    #     build: docker/conf/ldap
    #     container_name: ldap-server
    #     ports:
    #         - 389:389
    #         - 636:636
    #     environment:
    #         LDAP_ORGANISATION: "My Company"
    #         LDAP_DOMAIN: "my-company.com"
    #         LDAP_ADMIN_PASSWORD: "JonSn0w"
        
    # ldap-admin: 
    #     #http://phpldapadmin.sourceforge.net/wiki/index.php/LDAP_server_definitions
    #     #http://phpldapadmin.sourceforge.net/wiki/index.php/Config.php
    #     image: osixia/phpldapadmin:0.9.0 #phpLDAPadmin 1.2.5
    #     container_name: ldap-admin
    #     ports:
    #         - 6443:443
    #     #environment:
    #     #    PHPLDAPADMIN_LDAP_HOSTS: ldap-server
    #     #PHPLDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" phpldapadmin-service)
    #     volumes:
    #         - ${WEBSERVER}/zend-laminas-ex/docker/conf/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
    #     #depends_on:
    #     #    - ldap-server
    #     #command: --copy-service

    # laminas-NOT-USED:
    #     build: docker/conf/apache
    #     dockerfile: Dockerfile
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - .:/var/www

networks:
    zend:
        driver: bridge