version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        #container_name: nginx
        ports:
            - 82:80
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        networks: 
            - zend
          
    phpfpm: 
        build: .docker/conf/fpm
        working_dir: /appli
        ports: 
            - 9002:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
        networks: 
            - zend
    
    ldap-server:
        build: docker/conf/ldap
        container_name: ldap-server
        ports:
            - 389:389
            - 636:636
        environment:
            LDAP_ORGANISATION: "My Company"
            LDAP_DOMAIN: "my-company.com"
            LDAP_ADMIN_PASSWORD: "JonSn0w"
        
    ldap-admin: 
        image: osixia/phpldapadmin:0.9.0 #phpLDAPadmin 1.2.5
        ports:
            - 6443:443
        #environment:
        #    PHPLDAPADMIN_LDAP_HOSTS: ldap-server
        #PHPLDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" phpldapadmin-service)
        volumes:
            - ${WEBSERVER}/${DIRECTORY}/docker/conf/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
        depends_on:
           - ldap-server
        command: --copy-service

networks:
    zend:
        driver: bridge