# docker-compose-db.yml
version: "3"

services:
    ###############
    # DATABASE
    ################
    

    mongo:
        image: mongo:4.0
        #build: .docker/df/mongo
        container_name: mongo
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - mongo-v:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            # ME_CONFIG_MONGODB_USERNAME: user
            # ME_CONFIG_MONGODB_PASSWORD: pass

    redis:
        image: redis:6.0
        restart: always
        ports:
            - 6379:6379
        volumes: 
            - /TMAID/.data/redis/:/data/
            - /TMAID/.docker/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
        networks:
            - web
    
    memcached:
        image: memcached:1.6
        restart: always
        ports:
            - 11211:11211
        networks:
            - web

networks: 
    web:

volumes:
    mongo-v: