version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        container_name: nginx
        volumes:
            - ${WEBSERVER}/zend-laminas-ex:/usr/share/nginx/html
            - ${WEBSERVER}/zend-laminas-ex/docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - phpfpm
        ports:
            - "80:80"
          
    phpfpm: 
        build: ./conf/fpm
        container_name: phpfpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9000:9000
        volumes:
            - ${WEBSERVER}/zend-laminas-ex:/usr/share/nginx/html
        #depends_on: 
        #    - ldap-server
    
    # ldap-server:
    #     build: ./conf/ldap
    #     container_name: ldap-server
    #     ports:
    #         - 389:389
    #         - 636:636
    #     environment:
    #         LDAP_ORGANISATION: "My Company"
    #         LDAP_DOMAIN: "my-company.com"
    #         LDAP_ADMIN_PASSWORD: "JonSn0w"
        
    # ldap-admin: 
    #     #http://phpldapadmin.sourceforge.net/wiki/index.php/LDAP_server_definitions
    #     #http://phpldapadmin.sourceforge.net/wiki/index.php/Config.php
    #     image: osixia/phpldapadmin:0.9.0 #phpLDAPadmin 1.2.5
    #     container_name: ldap-admin
    #     ports:
    #         - 6443:443
    #     #environment:
    #     #    PHPLDAPADMIN_LDAP_HOSTS: ldap-server
    #     #PHPLDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" phpldapadmin-service)
    #     volumes:
    #         - ${WEBSERVER}/zend-laminas-ex/docker/conf/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
    #     #depends_on:
    #     #    - ldap-server
    #     #command: --copy-service